# Generated by Django 5.0.6 on 2024-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='is_running',
        ),
        migrations.AddField(
            model_name='jobs',
            name='success',
            field=models.BooleanField(default=False),
        ),
    ]
