# Generated by Django 5.0.6 on 2024-06-09 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_task_tasks_rename_job_id_tasks_job'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='coin_name',
            new_name='coin',
        ),
    ]
